/**
 * Represents a transaction record
 */
export interface Transaction {
    /** Autogenerated id of the transaction */
    id: string;
    /** Full name of the person associated with the transaction */
    person: string;
    /** Transaction date in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.sZ) */
    date: string;
    /** Transaction amount in USD */
    amount: number;
    /** Current status of the transaction */
    status: 'Completed' | 'In Progress' | 'Cancelled';
}
